// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string event_terminou_fase_2 = "CgkItLTV7IINEAIQEA"; // <GPGSID>
        public const string achievement_amigo = "CgkItLTV7IINEAIQAw"; // <GPGSID>
        public const string achievement_dias_seguidos = "CgkItLTV7IINEAIQCQ"; // <GPGSID>
        public const string event_moedas_dobrar = "CgkItLTV7IINEAIQCw"; // <GPGSID>
        public const string achievement_iniciou_a_aventura = "CgkItLTV7IINEAIQAA"; // <GPGSID>
        public const string achievement_anjo_gabriel = "CgkItLTV7IINEAIQDQ"; // <GPGSID>
        public const string event_moedas_fase_bloqueada = "CgkItLTV7IINEAIQEw"; // <GPGSID>
        public const string leaderboard_mestres_da_bblia = "CgkItLTV7IINEAIQAQ"; // <GPGSID>
        public const string achievement_discpulo = "CgkItLTV7IINEAIQFA"; // <GPGSID>
        public const string event_achivement = "CgkItLTV7IINEAIQGQ"; // <GPGSID>
        public const string achievement_belm = "CgkItLTV7IINEAIQBw"; // <GPGSID>
        public const string achievement_zacarias_e_isabel = "CgkItLTV7IINEAIQFQ"; // <GPGSID>
        public const string achievement_joo_batista = "CgkItLTV7IINEAIQCA"; // <GPGSID>
        public const string achievement_poder_do_tempo = "CgkItLTV7IINEAIQCg"; // <GPGSID>
        public const string achievement_poder_do_gelo = "CgkItLTV7IINEAIQBQ"; // <GPGSID>
        public const string achievement_estudante_nota_10 = "CgkItLTV7IINEAIQDg"; // <GPGSID>
        public const string event_leadeaboard = "CgkItLTV7IINEAIQGA"; // <GPGSID>
        public const string achievement_trs_estrelas = "CgkItLTV7IINEAIQBA"; // <GPGSID>
        public const string achievement_msicas_para_deus = "CgkItLTV7IINEAIQDw"; // <GPGSID>
        public const string event_iniciou_o_jogo = "CgkItLTV7IINEAIQBg"; // <GPGSID>
        public const string event_terminou_fase_5 = "CgkItLTV7IINEAIQFg"; // <GPGSID>
        public const string event_terminou_fase_4 = "CgkItLTV7IINEAIQEg"; // <GPGSID>
        public const string event_terminou_fase_6 = "CgkItLTV7IINEAIQFw"; // <GPGSID>
        public const string event_terminou_fase_1 = "CgkItLTV7IINEAIQDA"; // <GPGSID>
        public const string event_terminou_fase_3 = "CgkItLTV7IINEAIQEQ"; // <GPGSID>

}

